backend:
  name: git-gateway
  branch: master
media_folder: public/img
site_url: https://kyoung.codes
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    preview_path: "blog/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "relation", multiple: true, collection: "tags", searchFields: ["title"], valueField: "title", displayFields: "title", required: false}
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    preview_path: "portfolio/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "relation", multiple: true, collection: "tags", searchFields: ["title"], valueField: "title", displayFields: "title", required: false}
  - name: "tags"
    label: "Tags"
    folder: "content/tags"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
  - name: "about"
    label: "About Me"
    folder: "content/about"
    preview_path: "about"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}